spring:
  application:
    name: search-service
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      maxActive: -1
      maxWait: -1
      maxIdle: 100
      minIdle: 0
    timeout: 100
  data:
    solr:
      host: http://localhost:8983/solr/mycore
  zipkin:
      base-url: http://localhost:9411

server:
  port: 8002
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false

#spring.data.solr.host=http://192.168.1.44:8983/solr/e-commerce
#spring.data.solr.host=http://localhost:8983/solr/mycore