server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#logging:
#   config: classpath:logback-spring.xml
#   file: E:/untitled/e.log

#logging:
#  path: E:/untitled
